import test from 'node:test';
import assert from 'node:assert/strict';
import {weatherSnapshot,coordinates,WEATHER_PROMPT} from '../../netlify/functions/_lib/nowcast-weather.mjs';
import {liveAvatarService} from '../../netlify/functions/_lib/nowcast-liveavatar.mjs';
const now=Date.parse('2026-10-09T14:00:00Z');
const period={name:'Today',startTime:'2026-10-09T09:00:00-05:00',endTime:'2026-10-09T18:00:00-05:00',temperature:80,temperatureUnit:'F',windSpeed:'10 mph',windDirection:'NE',shortForecast:'Chance Rain',detailedForecast:'A 30 percent chance of rain.'};
function fixture(overrides={}) {
  const records={
    '/points/':{properties:{timeZone:'America/Chicago',relativeLocation:{properties:{city:'Orange Beach',state:'AL'}},forecast:'https://api.weather.gov/forecast',forecastHourly:'https://api.weather.gov/hourly',observationStations:'https://api.weather.gov/stations'}},
    '/forecast':{properties:{updateTime:new Date(now).toISOString(),periods:[period]}},
    '/hourly':{properties:{updateTime:new Date(now).toISOString(),periods:Array.from({length:24},(_,i)=>({...period,startTime:new Date(now+i*3600000).toISOString(),endTime:new Date(now+(i+1)*3600000).toISOString(),probabilityOfPrecipitation:{value:30}}))}},
    '/alerts/active':{features:[]},'/stations':{features:[{id:'https://api.weather.gov/stations/KJKA'}]},
    '/stations/KJKA/observations/latest':{properties:{timestamp:new Date(now-1800000).toISOString(),temperature:{value:25,unitCode:'wmoUnit:degC'},windSpeed:{value:16,unitCode:'wmoUnit:km_h-1'},textDescription:'Cloudy'}},
    '/tropical/':{features:[]},...overrides
  };
  return async url=>{const path=new URL(url).pathname;let key=Object.keys(records).sort((a,b)=>b.length-a.length).find(k=>path.startsWith(k));if(!key)throw new Error('Unexpected '+url);if(records[key] instanceof Error)throw records[key];return new Response(JSON.stringify(records[key]));};
}
test('coordinates reject strings, missing values, infinities and impossible places',()=>{for(const v of [null,{lat:'30',lon:-87},{lat:NaN,lon:0},{lat:91,lon:0},{lat:0,lon:181}])assert.throws(()=>coordinates(v));assert.deepEqual(coordinates({lat:30.29444,lon:-87.57361}),{lat:30.2944,lon:-87.5736});});
test('fresh briefing preserves provenance, units and per-session variable limits',async()=>{const weather=await weatherSnapshot({lat:30,lon:-87},fixture(),now);assert.match(weather.briefing,/77 degrees Fahrenheit/);assert.match(weather.briefing,/What are you planning today/);assert.equal(weather.alertCount,0);assert.equal(weather.variables.briefing,weather.briefing);for(const value of Object.values(weather.variables))assert.ok(value.length<=1000);assert.match(WEATHER_PROMPT,/\$\{hours4\}/);});
test('failed alert feed never becomes an all-clear',async()=>{const w=await weatherSnapshot({lat:30,lon:-87},fixture({'/alerts/active':new Error('outage')}),now);assert.equal(w.alertCount,null);assert.match(w.briefing,/warning status is unknown/);assert.match(w.variables.alerts,/UNAVAILABLE/);});
test('stale observation is not presented as current',async()=>{const w=await weatherSnapshot({lat:30,lon:-87},fixture({'/stations/KJKA/observations/latest':{properties:{timestamp:'2026-10-08T14:00:00Z',temperature:{value:25,unitCode:'wmoUnit:degC'}}}}),now);assert.doesNotMatch(w.briefing,/77 degrees/);assert.match(w.briefing,/fresh station observation is unavailable/);assert.ok(w.warnings.some(x=>x.includes('stale')));});
test('empty or failed forecasts stop a briefing honestly',async()=>{await assert.rejects(()=>weatherSnapshot({lat:30,lon:-87},fixture({'/forecast':new Error('outage'),'/hourly':{properties:{periods:[]}}}),now),/forecast could not be loaded/);});
test('provider-supplied external links cannot become server fetches',async()=>{const f=fixture({'/points/':{properties:{forecast:'https://evil.example/weather',forecastHourly:'https://evil.example/hourly'}}});await assert.rejects(()=>weatherSnapshot({lat:30,lon:-87},f,now),/forecast could not be loaded/);});
test('long official alerts stay within LiveAvatar dynamic-variable limits',async()=>{const features=Array.from({length:9},()=>({properties:{event:'Hurricane Warning',sent:new Date(now).toISOString(),expires:new Date(now+3600000).toISOString(),description:'A'.repeat(6000),instruction:'B'.repeat(6000)}}));const w=await weatherSnapshot({lat:30,lon:-87},fixture({'/alerts/active':{features}}),now);for(const value of Object.values(w.variables))assert.ok(value.length<=1000);assert.match(w.variables.alerts,/Count 9/);assert.match(w.variables.alert1,/Excerpt/);});
test('FULL mode resolves existing natural voice and exact weather context; no external speech provider',async()=>{
  const requests=[];const f=async(url,options)=>{const path=new URL(url).pathname;requests.push({path,body:options.body?JSON.parse(options.body):null});const data=path==='/v1/voices'?{results:[{id:'voice',name:'Ryan Natural'}]}:path==='/v1/contexts'?{results:[{id:'context',name:'Ryangineer Nowcast weather presenter v1'}]}:path==='/v1/contexts/context'?{id:'context',prompt:WEATHER_PROMPT,opening_text:'${briefing}'}:path==='/v1/sessions/token'?{session_token:'temporary',session_id:'session'}:null;return new Response(JSON.stringify({data}));};
  const create=liveAvatarService(f),w=await weatherSnapshot({lat:30,lon:-87},fixture(),now);const result=await create(w,{NOWCAST_LIVEAVATAR_API_KEY:'secret',NOWCAST_LIVEAVATAR_ID:'avatar',NOWCAST_LIVEAVATAR_VOICE_ID:'voice'});assert.equal(result.mode,'FULL');const token=requests.find(r=>r.path==='/v1/sessions/token').body;assert.equal(token.avatar_persona.voice_id,'voice');assert.equal(token.avatar_persona.context_id,'context');assert.equal(token.dynamic_variables.location,w.variables.location);assert.equal(token.max_session_duration,120);assert.equal(token.memory,undefined);assert.equal(requests.filter(r=>r.body && r.path==='/v1/contexts').length,0);await create(w,{NOWCAST_LIVEAVATAR_API_KEY:'secret',NOWCAST_LIVEAVATAR_ID:'avatar',NOWCAST_LIVEAVATAR_VOICE_ID:'voice'});assert.equal(requests.filter(r=>r.path==='/v1/voices').length,0);
});
test('Ridian credentials cannot configure the independent Nowcast system',async()=>{await assert.rejects(()=>liveAvatarService()({},{LIVEAVATAR_API_KEY:'legacy',RIDIAN_MOMENTUM_LIVEAVATAR_ID:'coach'}),/not configured/);await assert.rejects(()=>liveAvatarService()({},{NOWCAST_LIVEAVATAR_API_KEY:'secret',NOWCAST_LIVEAVATAR_ID:'avatar'}),/voice is not configured/);});
test('new context stores only the reusable prompt, with weather supplied to the token',async()=>{
  const calls=[];const f=async(url,options)=>{const path=new URL(url).pathname,body=options.body?JSON.parse(options.body):null;calls.push({path,body});const data=path==='/v1/voices'?{results:[{id:'voice',name:'Ryan Natural'}]}:path==='/v1/contexts'?(body?{id:'new-context'}:{results:[]}):{session_token:'token',session_id:'s'};return new Response(JSON.stringify({data}));};const w=await weatherSnapshot({lat:30,lon:-87},fixture(),now);await liveAvatarService(f)(w,{NOWCAST_LIVEAVATAR_API_KEY:'secret',NOWCAST_LIVEAVATAR_ID:'avatar',NOWCAST_LIVEAVATAR_VOICE_ID:'voice'});const context=calls.find(c=>c.path==='/v1/contexts' && c.body).body;assert.equal(context.prompt,WEATHER_PROMPT);assert.equal(context.opening_text,'${briefing}');assert.doesNotMatch(JSON.stringify(context),/30\.294|2026-10-09/);
});

import {createHandler,allowedOrigin} from '../../netlify/functions/nowcast-presenter.mjs';
const origin='https://www.ryangineer.com';
const request=(body,source=origin)=>new Request(origin+'/.netlify/functions/nowcast-presenter',{method:'POST',headers:{origin:source,'content-type':'application/json'},body});
test('endpoint is same-site and rejects Ridian, hostile and missing origins',()=>{for(const source of ['https://ridiantechnologies.com','https://evil.example','https://www.ryangineer.com.evil.example'])assert.equal(allowedOrigin(request('{}',source),{}),false);assert.equal(allowedOrigin(request('{}'),{}),true);assert.equal(allowedOrigin(new Request(origin),{}),false);assert.equal(allowedOrigin(request('{}','https://deploy-preview-19--reverent-mahavira-a88a48.netlify.app'),{}),true);});
test('endpoint rejects malformed and oversized bodies before weather or provider calls',async()=>{let called=0;const handler=createHandler({env:{},getWeather:()=>{called++;},mintSession:()=>{called++;}});for(const [body,status] of [['bad',400],['x'.repeat(1025),413],['{"action":"invalid"}',400]])assert.equal((await handler(request(body))).status,status);assert.equal(called,0);assert.equal((await handler(new Request(origin))).status,405);});
test('read briefing requires no provider configuration and keeps prompt variables private',async()=>{let minted=0;const handler=createHandler({env:{},getWeather:async()=>({briefing:'Fresh briefing',variables:{location:'server-only'}}),mintSession:()=>{minted++;}});const response=await handler(request('{"action":"briefing","lat":30,"lon":-87}'));assert.equal(response.status,200);assert.deepEqual(await response.json(),{weather:{briefing:'Fresh briefing'}});assert.equal(minted,0);assert.match(response.headers.get('cache-control'),/no-store/);});
test('disabled avatar and repeated starts do not create unbounded provider sessions',async()=>{let minted=0;const deps={getWeather:async()=>({briefing:'Fresh',variables:{}}),mintSession:async()=>{minted++;return {sessionToken:'temporary'};}};const body='{"action":"start","lat":30,"lon":-87}';assert.equal((await createHandler({...deps,env:{NOWCAST_AVATAR_ENABLED:'false'}})(request(body))).status,503);const handler=createHandler({...deps,env:{}});for(let i=0;i<5;i++)assert.equal((await handler(request(body))).status,200);assert.equal((await handler(request(body))).status,429);assert.equal(minted,5);});
